### ISSUE TITLE
Error in /api/execute: Status 400, CastError

### ISSUE THREAD

**Issue by bolandka** [infolis/infolis-web#41] opened 2015-11-19 19:27 UTC
Error: CastError: Cast to string failed for value \\"[object Object]\\" at path \\"tagMap\\"\n  at /home/infolis-web/mongoose-jsonld/src/handlers/restful.coffee:133:21

to reproduce, post for example the text extraction example at https://github.com/infolis/infolis-web/wiki/API-calls-to-algorithms

**Comment by kba** [comment] 2015-11-19 22:17
Caused by https://github.com/infolis/infoLink/issues/39, should be fixed by https://github.com/infolis/infoLink/pull/41

**Closed as completed by kba** 2015-11-19 22:17 UTC
Labels: bug
