### ISSUE TITLE
both pdf and text infolisFiles have tags now: what to select as input files?

### ISSUE THREAD

**Issue by bolandka** [infolis/infolis-web#59] opened 2015-11-21 13:40 UTC
It's an important feature to be able to set tags for uploaded files (thanks for adding this functionality in https://github.com/infolis/infolis-web/issues/56 :) ), but now the pdf files have tags and assign the same tags to their text files after tag extraction... both are InfolisFiles. When selecting files by tags, we will thus have a mixture of pdf and text files as inputFiles, right?

Seems to be the case, tried it here:
http://infolis.gesis.org/infolink/api/execution/d722b710-9053-11e5-b48b-955c13d7ab6d

Suggestion for a quick fix: when uploading, set tags for TextExtractor's execution, don't assign them to the pdf files' InfolisFiles directly?

**Comment by kba** [comment] 2015-11-21 13:43
yup :( As we discussed earlier, copying tags for generated resources can have grim consequences. Making the TagResolver prefer textFiles just adds more complexity.

**Comment by zuphilip** [comment] 2015-11-21 14:13
We could use another filter `mediaType` for selecting only text files, e.g. http://infolis.gesis.org/infolink/api/infolisFile?q=tags%3Azuphilip,mediaType%3Atext/plain . Or do I miss the point here?

**Comment by kba** [comment] 2015-11-21 15:11
The problem is that our serialiation/data model precludes non-class map structures that would be required to create proper queries. Therefore we resorted to embedding the query into the execution (`infolisPatternTags`, `infolisFileTags`). This will be fixed when we have time to consider our options.

**Comment by bolandka** [comment] 2015-11-23 14:14
We should consider links between InfolisFiles files and take them into account: If you don't pay attention and assign tags to some files when converting them to text and then decide to create new files of them by applying the BibliographyExtractor and assign the same tags, you have no way of differentiating between them anymore. And when you use these tags, you will always have both sets mixed. Of course, we could all simply pay attention and not do that but we should not rely on this ;) Having information on how InfolisFiles relate to each other would be nice.

**Comment by kba** [comment] 2015-11-23 14:25
That's  where I see potential for some Triple-Pattern/SPARQL/MongoDB - ish approach: We can guarantee that order of inputFiles == order of outputFiles (in fact that was one of the reasons we've been using a JSON store). Hence, it's a question of finding a file a the object of  a triple (alas [not yet possible](https://github.com/infolis/infolis-web/issues/67)), i.e. in which execution it was created, at what position, from what file etc. pp.

**Comment by bolandka** [comment] 2015-11-23 14:50
Exactly :)

**Comment by kba** [comment] 2016-07-26 15:02
We've solved this using `infolisFileTags` and `infolisPatternTags`. It's not the prettiest solution but it works just fine and who needs flexibility when you can have robustness.

**Closed as completed by kba** 2016-07-26 15:02 UTC
