### ISSUE TITLE
Encoding issues when displaying entities

### ISSUE THREAD

**Issue by bolandka** [infolis/infolis-web#64] opened 2015-11-22 20:07 UTC
see http://infolis.gesis.org/infolink/api/textualReference/74b597d0-914f-11e5-b6a5-7ff80ae297d2)

is it an issue when displaying or before that?

**Comment by kba** [comment] 2015-11-22 20:23
I'll check whether it's stored right.

**Comment by stweil** [comment] 2015-11-22 22:37
In infoLink: file src/test/resources/examples/minimal-txt/41da55fa6d533c726ec1d543ac18978a: Non-ISO extended-ASCII text, with LF, NEL line terminators

It's obviously not UTF-8 encoded, like several other files under src/test/resources/examples.
Would a conversion to UTF-8 fix the problem?

**Comment by kba** [comment] 2015-11-22 22:46
it is stored with the broken umlauts:

```
{
        "_id" : "74b597d0-914f-11e5-b6a5-7ff80ae297d2",
        "leftText" : "�ber unionsb�rgerschaftsrelevante Einstellungen gibt das",
        "rightText" : "aus dem Jahr 1996. Die",
        "reference" : "Eurobarometer 46.0",
        "pattern" : "http://infolis.gesis.org/infolink/api/infolisPattern/d2ec7fc0-8f48-11e5-9bfb-37e8acc5d407",
        "mentionsReference" : "http://infolis.gesis.org/infolink/api/entity/744808f0-914f-11e5-b6a5-7ff80ae297d2",
        "rightWords" : [
                "aus",
                "dem",
                "Jahr",
                "1996.",
                "Die"
        ],
        "leftWords" : [
                "�ber",
                "unionsb�rgerschaftsrelevante",
                "Einstellungen",
                "gibt",
                "das"
        ],
        "__v" : 0
}
```

@stweil Those were generated by the same tools we're using for pdf-to-text. If we fix these test files our unit tests might work, but the problem isn't solved.

**Comment by bolandka** [comment] 2015-11-23 00:40
setting the java default file encoding to utf8 did the trick to solve encoding issues for textextraction on the server, lets see whether it can help here as well
(export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8), see https://github.com/infolis/infoLink/issues/28

**Comment by kba** [comment] 2015-11-30 16:21
This was fixed by setting the JAVA_TOOL_OPTIONS. Fix is documented in our devop pad, closing for now. Open a new issue if you encounter encoding issues on new resources.

**Closed as completed by kba** 2015-11-30 16:21 UTC
Labels: minor
